spring.application.name=bloco-api
spring.datasource.url=${url:jdbc:postgresql://localhost/bloco_api}
spring.datasource.username=${user:postgres}
spring.datasource.password=${password:123456}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
